-- AlterTable
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "hsnCode" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "isLimitedStock" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "isFestivePick" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "isExclusive" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "isOnlineOnly" BOOLEAN NOT NULL DEFAULT false;
